apiVersion: apps/v1
kind: Deployment

metadata:
  name: productcatalogservice
  namespace: shopsphere

  labels:
    app: productcatalogservice
    app.kubernetes.io/name: productcatalogservice
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: shopsphere
    app.kubernetes.io/managed-by: kubectl

spec:

  replicas: 2

  revisionHistoryLimit: 5

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: productcatalogservice

  template:

    metadata:

      labels:
        app: productcatalogservice
        app.kubernetes.io/name: productcatalogservice
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: shopsphere

    spec:

      terminationGracePeriodSeconds: 30

      containers:

      - name: productcatalogservice

        image: 221237748109.dkr.ecr.ap-south-1.amazonaws.com/shopsphere:productcatalogservice-v1

        imagePullPolicy: Always

        ports:

        - name: grpc
          containerPort: 3550

        env:

        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: shopsphere-config
              key: PORT

        - name: DISABLE_PROFILER
          valueFrom:
            configMapKeyRef:
              name: shopsphere-config
              key: DISABLE_PROFILER

        - name: DISABLE_TRACING
          valueFrom:
            configMapKeyRef:
              name: shopsphere-config
              key: DISABLE_TRACING

        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: shopsphere-config
              key: OTEL_EXPORTER_OTLP_ENDPOINT

        - name: OTEL_SERVICE_NAME
          value: "productcatalogservice"

        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: shopsphere-config
              key: OTEL_EXPORTER_OTLP_PROTOCOL

        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=productcatalogservice,deployment.environment=dev"

        resources:

          requests:
            cpu: 100m
            memory: 128Mi

          limits:
            cpu: 300m
            memory: 256Mi

        readinessProbe:

          tcpSocket:
            port: 3550

          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

        livenessProbe:

          tcpSocket:
            port: 3550

          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
