apiVersion: v1
kind: Service

metadata:
  name: paymentservice
  namespace: shopsphere

  labels:
    app: paymentservice
    app.kubernetes.io/name: paymentservice
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: shopsphere

spec:

  selector:
    app: paymentservice

  ports:

  - name: grpc
    protocol: TCP
    port: 50051
    targetPort: 50051

  type: ClusterIP
