apiVersion: v1
kind: Service

metadata:
  name: recommendationservice
  namespace: shopsphere

  labels:
    app: recommendationservice
    app.kubernetes.io/name: recommendationservice
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: shopsphere

spec:

  selector:
    app: recommendationservice

  ports:

  - name: grpc
    port: 8080
    targetPort: 8080
    protocol: TCP

  type: ClusterIP
