apiVersion: v1
kind: Service

metadata:
  name: shippingservice
  namespace: shopsphere

  labels:
    app: shippingservice
    app.kubernetes.io/name: shippingservice
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: shopsphere

spec:

  selector:
    app: shippingservice

  ports:

  - name: grpc
    protocol: TCP
    port: 50051
    targetPort: 50051

  type: ClusterIP
