apiVersion: v1
kind: Service

metadata:
  name: cartservice
  namespace: shopsphere

  labels:
    app: cartservice
    app.kubernetes.io/name: cartservice
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: shopsphere

spec:

  selector:
    app: cartservice

  ports:

  - name: grpc
    port: 7070
    targetPort: 7070
    protocol: TCP

  type: ClusterIP
